services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: captive_portal
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - SECRET_KEY=change-me-in-production  # Change this for production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
